plugins {
    id 'com.android.application'
}

android {
    namespace 'com.personalassistant.mobile'
    compileSdk 35

    defaultConfig {
        applicationId 'com.personalassistant.mobile'
        minSdk 23
        targetSdk 35
        versionCode 3666
        versionName '3.6.66-android'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
